; Auto-generated by scripts/build-installer.mjs
#define AppName "Auto Zoom Scheduler"
#define AppVersion "1.0.0"
#define AppPublisher "Auto Zoom Scheduler"
#define AppURL "https://example.invalid"

[Setup]
AppName={#AppName}
AppVersion={#AppVersion}
DefaultDirName={pf}\Auto Zoom Scheduler
DefaultGroupName={#AppName}
OutputDir=output
OutputBaseFilename=Setup
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=commandline
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
SetupLogging=yes

[Dirs]
Name: "{localappdata}\AutoZoomScheduler"
Name: "{localappdata}\AutoZoomScheduler\data"
Name: "{localappdata}\AutoZoomScheduler\screen"
Name: "{localappdata}\AutoZoomScheduler\logs"
Name: "{localappdata}\AutoZoomScheduler\credentials"

[Files]
Source: "staging\web\*"; DestDir: "{app}\web"; Flags: createallsubdirs recursesubdirs
Source: "staging\server\*"; DestDir: "{app}\server"; Flags: createallsubdirs recursesubdirs
Source: "staging\scripts\*"; DestDir: "{app}\scripts"; Flags: createallsubdirs recursesubdirs
Source: "staging\package.json"; DestDir: "{app}"
Source: "staging\start-worker.cmd"; DestDir: "{app}"
Source: "staging\SleepMode.exe"; DestDir: "{app}"

[Icons]
Name: "{userdesktop}\Auto Zoom Scheduler"; Filename: "{app}\web\index.html"; WorkingDir: "{app}\web"
Name: "{commonprograms}\Auto Zoom Scheduler"; Filename: "{app}\web\index.html"; WorkingDir: "{app}\web"
Name: "{userdesktop}\Sleep Mode"; Filename: "{app}\SleepMode.exe"; WorkingDir: "{app}"
Name: "{commonprograms}\Sleep Mode"; Filename: "{app}\SleepMode.exe"; WorkingDir: "{app}"

[Run]
Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\scripts\install-zoom-scheduler-tasks.ps1"""; WorkingDir: "{app}"; Flags: runhidden; Description: "Installing AutoZoom task scheduler entries"
Filename: "{app}\start-worker.cmd"; WorkingDir: "{app}"; Flags: runhidden; Description: "Starting the local worker"
Filename: "http://127.0.0.1:5173/"; Flags: shellexec; Description: "Open the Auto Zoom Scheduler dashboard"
